<div class="right_bar">
    <h2 style="background-color: #000;color:#fff;">Barra lateral</h2> 
    <p> Arquivo exclusivo para inclusão externa, com a extensão .INC </p>
    <?php 
    #indica o numero de linhas do script
    echo __LINE__ ."<hr>"; 
    #o nome e a localização do arquivo de script
    echo __FILE__ ."<hr>";
    #localização da pasta do script
    echo __DIR__ ."<hr>"
    ?>
    <p> Resultado dos <br>calculos do Form</p>
</div>